# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname dice
#' @export
fast_roll <- function(r) {
    .Call('_diceR_fast_roll', PACKAGE = 'diceR', r)
}

